### ISSUE TITLE
I am getting an error with firebase Failed to convert a value of type java.lang.String to int

### ISSUE THREAD

**Issue by adetheprince** [rajanvishwa10/Social-Media#1]
com.google.firebase.database.DatabaseException: Failed to convert a value of type java.lang.String to int
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper.convertInteger(CustomClassMapper.java:364)
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper.deserializeToPrimitive(CustomClassMapper.java:290)
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper.deserializeToClass(CustomClassMapper.java:215)
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper.convertToCustomClass(CustomClassMapper.java:80)
        at com.google.firebase.database.DataSnapshot.getValue(DataSnapshot.java:203)
        at com.android.socialmedia.ImageFragment$6.onDataChange(ImageFragment.java:228)
        at com.google.firebase.database.core.ValueEventRegistration.fireEvent(ValueEventRegistration.java:75)
        at com.google.firebase.database.core.view.DataEvent.fire(DataEvent.java:63)
        at com.google.firebase.database.core.view.EventRaiser$1.run(EventRaiser.java:55)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by adetheprince** [comment]
I have tried the demo firebase same error. looks like writing to the data or table error?

**Comment by rajanvishwa10** [comment]
Check your model class and firebase child nodes type. If you want to use string as int you can wrap it as Integer.parseInt();

**Comment by adetheprince** [comment]
I have not made any tables its all firebase auto wrote, when user is registered and post, or comment, can you show us the table structure please sorry new to firebase.

**Comment by adetheprince** [comment]
![image](https://user-images.githubusercontent.com/15795755/103279039-d3288d80-49c4-11eb-9f43-dff96ca1d730.png)

**Comment by rajanvishwa10** [comment]
add profileImages at registration and keep the value "" empty for later use
